### PR TITLE
Open nlp

### PR DESCRIPTION
**Pull request by griffinallen**

### CODE REVIEW

**Review by Braden-Saunders — APPROVED** [review]
Looks good, we can safety ignore the conflicts in the frontend folder because when we merge the front-end branch they will be resolved.

**Review by DanielGannage — COMMENTED** [review]
ready for merge

**Review by Drov3r — APPROVED** [review]
Multiple HMTL for archive in scraper folder

**Review by aidanLarock — APPROVED** [review]
Looks good, intent for first and last name works.

**Review by JJMGula — APPROVED** [review]
👍

**Pull request merged**
