### PR TITLE
Updated Player Scraping

### PR DESCRIPTION
**Pull request by aidanLarock**
Added live player scraping to the system. Using selenium, we can now find the url for player information.

### CODE REVIEW

**Review by Drov3r — APPROVED** [review]
No overlap in the folders i worked on

**Review by JJMGula — APPROVED** [review]
👍

**Review by DanielGannage — APPROVED** [review]
Scraper works well!

**Review by Braden-Saunders — APPROVED** [review]
Some minor overlap, but I will resolve it when merging, looks good!

**Pull request merged**
